"""Generate runtime CSS from appearance tokens."""

from __future__ import annotations

from .defaults import FONT_STACKS, RADIUS_MAP, font_stack


def hex_to_rgb(value: str | None) -> str:
	color = (value or "").strip().lstrip("#")
	if len(color) == 3:
		color = "".join(ch * 2 for ch in color)
	if len(color) != 6:
		return "15, 118, 110"
	try:
		return ", ".join(str(int(color[i : i + 2], 16)) for i in (0, 2, 4))
	except ValueError:
		return "15, 118, 110"


def mix_hex(value: str | None, toward: str, ratio: float) -> str:
	def parts(hex_color: str) -> tuple[int, int, int]:
		raw = hex_color.strip().lstrip("#")
		if len(raw) == 3:
			raw = "".join(ch * 2 for ch in raw)
		if len(raw) != 6:
			return (15, 118, 110)
		return tuple(int(raw[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]

	start = parts(value or "#0F766E")
	end = parts(toward)
	mixed = [round(start[i] * (1 - ratio) + end[i] * ratio) for i in range(3)]
	return "#{:02x}{:02x}{:02x}".format(*mixed)


def _theme_vars(tokens: dict, mode: str) -> str:
	"""Only override the key Frappe CSS variables that control branding."""
	primary = tokens.get("primary_color") or "#0F766E"
	text = tokens.get("text_color") or "#0F172A"
	muted = tokens.get("muted_text_color") or "#64748B"
	border = tokens.get("border_color") or "#E2E8F0"
	navbar = tokens.get("navbar_color") or "#FFFFFF"
	font = font_stack(tokens.get("font_family"))
	heading_font = font_stack(tokens.get("heading_font") or tokens.get("font_family"))
	base_size = tokens.get("base_font_size") or "14px"
	primary_dark = mix_hex(primary, "#000000" if mode == "light" else "#ffffff", 0.2)

	return f"""
	--primary-color: {primary};
	--brand-color: {primary};
	--primary: {primary};
	--text-color: {text};
	--heading-color: {text};
	--text-muted: {muted};
	--text-light: {muted};
	--border-color: {border};
	--dark-border-color: {border};
	--navbar-bg: {navbar};
	--font-stack: {font};
	--heading-font: {heading_font};
	--text-base: {base_size};
	--btn-primary-bg: {primary};
	--btn-primary-hover: {primary_dark};
	--sidebar-select-color: {mix_hex(navbar, primary, 0.08)};
"""


def _layout_vars(layout: dict) -> str:
	radius = RADIUS_MAP.get(layout.get("border_radius") or "Medium", RADIUS_MAP["Medium"])
	return f"""
	--border-radius-sm: {radius["sm"]};
	--border-radius: {radius["md"]};
	--border-radius-md: {radius["md"]};
	--border-radius-lg: {radius["lg"]};
	--border-radius-full: {radius["full"]};
"""


def _login_css(config: dict) -> str:
	background = config.get("login_background") or ""
	tagline = (config.get("tagline") or "").replace('"', '\\"')
	rules = []
	if background:
		rules.append(
			f'body[data-path="login"] {{ background-image: url("{background}"); background-size: cover; background-position: center; }}'
		)
	if tagline:
		rules.append(
			f'body[data-path="login"] .page-card-head h4::after {{ content: "{tagline}"; display: block; margin-top: 0.3rem; font-size: 0.82rem; font-weight: 400; color: var(--text-muted); }}'
		)
	return "\n".join(rules)


def _slug(value: str | None) -> str:
	return (value or "default").strip().lower().replace(" ", "-")


def generate_css(config: dict) -> str:
	light = config.get("light_tokens") or {}
	dark = config.get("dark_tokens") or {}
	layout = config.get("layout") or {}
	custom = config.get("custom_css") or ""

	fonts = {
		light.get("font_family"),
		light.get("heading_font"),
		dark.get("font_family"),
		dark.get("heading_font"),
	}
	imports = []
	for font in sorted(f for f in fonts if f and f != "System UI" and f in FONT_STACKS):
		family = font.replace(" ", "+")
		imports.append(
			f"@import url('https://fonts.googleapis.com/css2?family={family}:wght@400;500;600;700&display=swap');"
		)

	imports_css = "\n".join(imports)
	return f"""\
/* Generated by frappe_whitelabel — do not edit manually. */
{imports_css}

:root, [data-theme="light"] {{
{_theme_vars(light, "light")}
{_layout_vars(layout)}
}}

[data-theme="dark"] {{
{_theme_vars(dark, "dark")}
{_layout_vars(layout)}
}}

{_login_css(config)}

{custom}
""".strip()


def generate_print_css(config: dict) -> str:
	light = config.get("light_tokens") or {}
	primary = light.get("primary_color") or "#0F766E"
	text = light.get("text_color") or "#0F172A"
	muted = light.get("muted_text_color") or "#64748B"
	font = font_stack(light.get("font_family"))
	header = config.get("print_header_text") or config.get("product_name") or ""
	header = str(header).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
	css = f"""\
.print-format, .print-format * {{
	font-family: {font};
	color: {text};
}}
.print-format .print-heading, .print-format h1, .print-format h2, .print-format h3 {{
	color: {primary};
}}
.print-format .text-muted {{
	color: {muted} !important;
}}"""
	if header:
		css += f'\n.print-format::before {{ content: "{header}"; display: block; font-weight: 600; margin-bottom: 12px; color: {primary}; }}'
	return css
